server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeworkOne
    username: homeworkOne
    password: 123


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

upload:
  server:
    folder: .D:/gayratjon

api:
  jsonplaceholder: https://jsonplaceholder.typicode.com/

jwt:
  token:
    secret: hellojwttoken
    validity: 86400000
